version: "2.1"
services:
  anchor:
    container_name: anchor
    image: openjdk:17
    volumes:
      # 本地jar包路径
      - /root/docker/anchor.jar:/anchor.jar
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    # 访问端口
    ports:
      - "8080:8080"
      - "7050:7050"
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    # 新增健康检查
    healthcheck:
      test: [ "CMD", "curl", "-v", "http://localhost:8080" ] # 检测8080端口就绪
      interval: 10s
      timeout: 5s
      retries: 10
    # 启动容器后执行的命令
    entrypoint: java -jar anchor.jar
    # 指定IP地址
    networks:
      - default

  node1:
    # 指定容器名称
    container_name: node1
    # 重启机制
    # restart: always
    image: openjdk:17
    volumes:
      # 本地jar包路径
      - /root/docker/node1.jar:/node.jar
      - /root/docker/data/node1/:/data/node1/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    # 访问端口
    ports:
      - "8001:8001"
      - "7001:7001"
      - "7101:7101"
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    # 新增依赖条件
    depends_on:
      anchor:
        condition: service_healthy
    # 启动容器后执行的命令
    entrypoint: java -jar node.jar
    # 指定IP地址
    networks:
      - default

  node2:
    # 指定容器名称
    container_name: node2
    # 重启机制
    # restart: always
    image: openjdk:17
    volumes:
      # 本地jar包路径
      - /root/docker/node2.jar:/node.jar
      - /root/docker/data/node2/:/data/node2/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    # 访问端口
    ports:
      - "8002:8001"
      - "7002:7001"
      - "7102:7101"
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    # 新增依赖条件
    depends_on:
      anchor:
        condition: service_healthy
    # 启动容器后执行的命令
    entrypoint: java -jar node.jar
    # 指定IP地址
    networks:
      - default

  node3:
    # 指定容器名称
    container_name: node3
    # 重启机制
    # restart: always
    image: openjdk:17
    volumes:
      # 本地jar包路径
      - /root/docker/node3.jar:/node.jar
      - /root/docker/data/node3/:/data/node3/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    # 访问端口
    ports:
      - "8003:8001"
      - "7003:7001"
      - "7103:7101"
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    # 新增依赖条件
    depends_on:
      anchor:
        condition: service_healthy
    # 启动容器后执行的命令
    entrypoint: java -jar node.jar
    # 指定IP地址
    networks:
      - default

  node4:
    # 指定容器名称
    container_name: node4
    # 重启机制
    # restart: always
    image: openjdk:17
    volumes:
      # 本地jar包路径
      - /root/docker/node4.jar:/node.jar
      - /root/docker/data/node4/:/data/node4/
      # 指定容器时间为宿主机时间
      - /etc/localtime:/etc/localtime
    # 访问端口
    ports:
      - "8004:8001"
      - "7004:7001"
      - "7104:7101"
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    # 新增依赖条件
    depends_on:
      anchor:
        condition: service_healthy
    # 启动容器后执行的命令
    entrypoint: java -jar node.jar
    # 指定IP地址
    networks:
      - default

networks:
  default:
    driver: bridge